language: groovy

jdk:
  # - openjdk9
  - oraclejdk9
  - openjdk8

env:
  - TARGET=gant_groovy2.4:test
  - TARGET=gant_groovy2.5:test
  - TARGET=gant_groovy2.6:test
  # - TARGET=gant_groovy3.0:test

script:
  - ./gradlew $TARGET
